#!/bin/bash

start=1
end=70
embedding=X_joint_umap_features
test=read_depth_tests
outprefix=data/$test/results/2022-02-11_read-depth-test_
args_file=data/$test/configs/mira_test.txt

for ((i=$1;i<=$2;i++))
do
    echo "Dataset $i"
    python frankencell/test_algorithms/mira_test.py \
        @${args_file} \
        --data data/$test/datasets/rd_test_trial_${i}_data.h5ad \
        --out-prefix ${outprefix}${i} \
        --embedding-key ${embedding} > data/$test/logs/rd_test_trial_${i}_log.txt 2>&1
    python frankencell/evaluators/mira_eval.py \
        --data ${outprefix}${i}_results_adata.h5ad \
        --test-results ${outprefix}${i}_${embedding}_test-results.tsv \
        --out-prefix ${outprefix}${i} >> data/$test/logs/rd_test_trial_${i}_log.txt 2>&1
done